import Link from "next/link";

import { Expedient, formatDate, getApi } from "../../lib";

export default async function Detail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const response = await getApi<{ data: Expedient }>(`/expedients/${id}`);
  const item = response?.data;
  if (!item) {
    return <main><h1 className="text-3xl font-bold">Expediente no disponible</h1><p>Puede que aún no esté sincronizado.</p></main>;
  }
  return <main className="max-w-4xl space-y-6"><Link href="/expedientes" className="font-semibold text-paraguay">← Volver al listado</Link><header className="card"><p className="font-mono text-paraguay">{item.number}</p><h1 className="mt-3 text-3xl font-black">{item.title}</h1><p className="mt-4 text-slate-600">{item.chamber} · {item.type} · {item.status}</p></header><section className="grid gap-4 sm:grid-cols-3"><div className="card"><b>Etapa</b><p>{item.stage ?? "Sin datos"}</p></div><div className="card"><b>Ingreso</b><p>{formatDate(item.filed_on)}</p></div><div className="card"><b>Frescura</b><p>{formatDate(item.synced_at)}</p></div></section><section className="card"><h2 className="text-xl font-bold">Autores</h2>{item.authors?.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{item.authors.map((author) => <article key={author.name} className="relation-card"><b>{author.name}</b><span>{[author.party, author.chamber?.replace("CAMARA DE ", "")].filter(Boolean).join(" · ") || "Autor registrado por SILpy"}</span></article>)}</div> : <p className="mt-3 text-slate-600">Los autores se incorporarán con la próxima sincronización de detalle.</p>}</section><section className="card"><h2 className="text-xl font-bold">Comisiones</h2><p className="mt-3">{item.committees?.join(" · ") || "Sin comisiones publicadas para este expediente."}</p></section><section className="card"><h2 className="text-xl font-bold">Documentos adjuntos</h2>{item.attachments?.length ? <ul className="mt-4 space-y-2">{item.attachments.map((attachment) => <li key={attachment.id} className="attachment-row"><span>PDF · {attachment.info ?? "Documento de iniciativa"}</span>{attachment.url && <a className="font-semibold text-paraguay underline" href={attachment.url} target="_blank" rel="noreferrer">Abrir documento ↗</a>}</li>)}</ul> : <p className="mt-3 text-slate-600">Los documentos se incorporarán con la próxima sincronización de detalle.</p>}{item.source_url && <a className="mt-5 inline-block text-sm font-semibold text-paraguay" href={item.source_url} target="_blank" rel="noreferrer">Ver ficha original SILpy ↗</a>}</section></main>;
}
